pipeline {
    agent any
  
    stages {
        stage('Check Docker Network') {
            steps {
                script {
                    def networkExists = sh(script: 'docker network inspect lmsnetwork > /dev/null 2>&1', returnStatus: true)
                    if (networkExists == 0) {
                        echo 'Docker network lmsnetwork already exists'
                    } else {
                        sh 'docker network create -d bridge lmsnetwork'
                    }
                }
            }
        }

        stage('Check Database Container') {
            steps {
                script {
                    def containerExists = sh(script: 'docker inspect -f {{.state.Running}} mysql', returnStatus: true)
                    if (containerExists == 0) {
                        echo 'MYSQL container already exists'
                    } else {
                        sh 'docker container run -d --name mysql --network lmsnetwork -e MYSQL_ROOT_PASSWORD=Lms@12345 -p 3306:3306 mysql:latest'
                    }    
                }
            }
        }
        

        stage('Email notification') {
            steps {
                script {
                    emailext attachmentsPattern: 'build.log',
                              body: 'Build successful',
                              subject: 'Jenkins Notification - Build Successful',
                              to: 'sathishgodavarthi89@gmail',  
                              attachLog: true,
                              compressLog: true
                }
            }
        }

    }
} 
       
    

               

