pipeline {
    agent any
        
    stages {
        stage('Sonar Analysis') {
            steps {
                script {
                    echo 'Running Maven clean, verify, and SonarQube analysis...'
                    sh 'cd LMS-BE/ && mvn clean verify sonar:sonar ' +
                            "-Dsonar.projectKey=lms-java " +
                            "-Dsonar.projectName='lms-java' " +
                            "-Dsonar.host.url=http://13.236.84.113:9000 " +
                            "-Dsonar.login=sqp_9857a9e70109074ce7add064e16cecfece91f194 " +
                            "-DskipTests "
                }
            }
        }

        stage('Email notification') {
             steps {  
                script {
                    emailext attachmentsPattern: 'build.log',
                              body: 'This is to notify that the build job has been successful.\n\nBuild URL: ${BUILD_URL}',
                              subject: 'Jenkins Notification - Build Successful',
                              to: 'sathishgodavarthi89@gmail.com',
                              cc: 'muralialakuntla3@gmail.com',
                              bcc: '',
                              replyTo: '',
                              recipientProviders: [[$class: 'DevelopersRecipientProvider']],
                              attachLog: true,
                              compressLog: true
            }
        }
    }

    post {
        success {
            script {
                // Additional success post-build actions if needed
            }
        }
    }
}
}