pipeline {
    agent any
  
    stages {
        stage('Check Docker Network') {
            steps {
                script {
                    def networkExists = sh(script: 'docker network inspect lmsnetwork > /dev/null 2>&1', returnStatus: true)
                    if (networkExists == 0) {
                        echo 'Docker network lmsnetwork already exists'
                    } else {
                        sh 'docker network create -d bridge lmsnetwork'
                    }
                }
            }
        }

        stage('Email notification') {
            steps {
                script {
                    emailext attachmentsPattern: 'build.log',
                              body: 'Build successful',
                              subject: 'Jenkins Notification - Build Successful',
                              to: 'sathishgodavarthi89@gmail',  
                              attachLog: true,
                              compressLog: true
                }
            }
        }

        stage('Email notification') {
            steps {
                script {
                    emailext attachmentsPattern: 'build.log',
                              body: 'Build Filure',
                              subject: 'Jenkins Notification - Build Filure',
                              to: 'sathishgodavarthi89@gmail',  
                              attachLog: true,
                              compressLog: true
                }
            }
        }
    }
}
               

